### ISSUE TITLE
Switch walls and toggle walls lack identifying attributes aside from color

### ISSUE THREAD

**Issue by ncrecc** [eevee/lexys-labyrinth#25]
This isn't super high-priority since they're distinguishable anyway in most forms of colorblindness, but in grayscale they look nearly identical.
![image](https://user-images.githubusercontent.com/11216597/104820101-abc52380-5800-11eb-829d-acfdf87aca7b.png)
Also, unlike CC2's default tileset, the color of powered wire is unrelated to the color of switch walls, which might be slightly confusing.

**Comment by eevee** [comment]
Yeah, I've been meaning to fix this.  It's hard to do with the base CC2 tileset, since both kinds of wall use the same static overlay in wall mode, so I can't just draw a symbol on top to distinguish them.  That leaves either changing the border animation, or doing something exceptionally clever so that the wall overlay makes a different pattern depending on which tile it's overlaid on.

**Comment by eevee** [comment]
fixed in 20e67b4 (the outline now goes through three colors for switch walls)
