### ISSUE TITLE
Wishlist: Implementation of "Hide Logic" option

### ISSUE THREAD

**Issue by idarob** [eevee/lexys-labyrinth#52]
Hide logic in CC2 makes wire, wire tunnels, logic gates, counters, and pink and black buttons invisible while on/of switches and switch doors/purple toggle walls (and grey buttons and the lightning bolt) remain visible. Picking up the secret eye lets the player view everything as if hide logic was not activated.
The option to hide logic is useful sometimes for aestethic reasons and sometimes for not spoiling a puzzle.

**Comment by eevee** [comment]
note that, as implemented, pink and black buttons will still remain visible in LL — hiding _buttons_ seems ludicrous to me and i've seen it in lists of CC2 bugs, so i'm assuming it is one, unless someone has a really compelling reason why it's not!  otherwise this should be good

didn't know the secret eye revealed wires, that's pretty clever actually
