### ISSUE TITLE
Cerise's forward-facing sprites feel a bit suggestive

### ISSUE THREAD

**Issue by ncrecc** [eevee/lexys-labyrinth#55]
Was hesitant about bringing this up since I didn't want it to sound like "back ye wretched sinner, purge these evil images before they provoke unchristian thoughts!" (or "no, see, suggestiveness is fine until it's furries"), but the way Cerise's breasts are openly visible and highlighted seems a bit too suggestive for a general audience. I also think the shading under her belly button draws some attention to her nether regions, but that could just be me. Neither of the main characters are wearing clothes, of course, but Lexy's fur covers her chest, and her breasts(?) in her side sprite also look like just a tuft of fur sticking out.
(The ending screen can stay as-is - CC Lynx (and most ports) had Melinda in a suggestive pose in the end screen, and players seeing the end screen is uncommon anyway.)

**Comment by ncrecc** [comment]
I guess if it's a fox flux derivative it's not *supposed* to be squeaky clean but making it clean might make it more accessible as an emulator

**Comment by eevee** [comment]
the sprite in question:

![image](https://user-images.githubusercontent.com/94112/109445323-8da43300-79fc-11eb-8389-bffa092d4135.png)

i don't see it.  there are no nipples in this design, so there's nothing to suggest.  her chest has highlights because otherwise the form doesn't make sense.  the shading under the belly button is a single line of pixels on a curve that faces away from the light source, no different from lexy.

she's just a cartoon bunny person.  there's nothing here even remotely inappropriate, and at this tiny scale it would take some creative effort to even truly be suggestive.  case in point, lexy doesn't have breasts; that _is_ fur, just like the curve on her back.

**Comment by ncrecc** [comment]
sorry :(

**Comment by eevee** [comment]
it's np, sorry if that comment sounded brusque
