### ISSUE TITLE
Blue key disappears in CCLP3 level 54

### ISSUE THREAD

**Issue by TheJakeSchmidt** [eevee/lexys-labyrinth#7]
I think https://github.com/eevee/lexys-labyrinth/commit/36b9f2efd7b511e769d4b6616734a4db5390c271 broke CCLP3 level 54 "Good Advice" (https://wiki.bitbusters.club/Good_Advice). The level has a blue key at (21, 16), which has several gliders in its vicinity at startup. By the time I get there, the blue key has disappeared, having been erased by one of the gliders (I assume), and I can't make further progress on the level.

**Comment by chz16** [comment]
That change did in fact break Good Advice. Unfortunately, that change is correct behavior; the problem is that enemy behavior is emulated incorrectly and a glider gets turned around and eats the key when it shouldn't. It's *possible* that a relatively straightforward change to the order actors are processed might fix it (and other levels), or it might be a hideous nightmare. Fun!

**Comment by eevee** [comment]
Hallelujah!  Reversing actor order does indeed fix this.  Let's just hope it doesn't break a bunch of other stuff lololol sob

**Comment by TheJakeSchmidt** [comment]
Incredible turnaround. Thanks for debugging and fixing!
