### ISSUE TITLE
Sound does not work on desktop Safari

### ISSUE THREAD

**Issue by snacksforsale** [eevee/lexys-labyrinth#73]
I am using Safari 14.0.3 on macOS 11.2.3. I checked Firefox 87.0 and sound does work on that browser. I understand that tons of people hate Safari for many reasons and I personally don't mind playing without sound so I'm sure this is not a priority for anyone. I am submitting a ticket anyway in case I (or someone else) want(s) to take a crack at this at any point in the future.

**Comment by eevee** [comment]
Apple adamantly refuses to support the royalty-free Ogg formats in Safari (the _only_ browser with this problem), instead opting to promote patent-encumbered MPEG formats for what I can only assume are business reasons.  If the richest company in the history of humanity insists on making their products worse in order to pad their bottom line through some bizarre chess game they want to play with developers, that's entirely their prerogative, but I won't help them with it.

It used to be possible to install a QuickTime Ogg codec, but it sounds like Apple has [removed that capability entirely](https://www.xiph.org/quicktime/).
